# sample synergy configuration file
#
# comments begin with the # character and continue to the end of
# line.  comments may appear anywhere the syntax permits.

section: screens
	# three hosts named:  moe, larry, and curly
	maclaptop:
	supermaquina:
	curly:
end

section: links
	# larry is to the right of moe and curly is above moe
	maclaptop:
		right = supermaquina
        supermaquina:
		left = maclaptop
end

section: aliases
	maclaptop:
		davi-macbookpro
		davi-macbookpro.local
end
