set-option -g prefix C-t
unbind-key C-b
bind-key C-t send-prefix
setw -g mouse on
# set-option -g status-position top
set-option -g mode-keys vi
set-option -g status-keys vi
set -g default-terminal "screen-256color"
set -g base-index 1
set-window-option -g window-status-current-bg red

# http://mutelight.org/articles/practical-tmux
setw -g aggressive-resize on
