#!/bin/sh -x
tmux has-session -t work && exit -1
tmux new-session -d -s work
tmux new-window -n code -t work:2 /bin/bash
tmux kill-window -t work:1
tmux new-window -n vim -t work:1 /usr/bin/vim
tmux split-window -v -p 30 -t work:2 /bin/bash
