#!/bin/sh
name=$0
term=${1:-xterm}
shell=${2:-/bin/bash}
session=${3:-work}
export TERM=screen-256color-bce
# code below is buggy
tmux -2 list-clients -t $session
if [ $? -eq 0 ]; then
  exec -a $name $term -e tmux -2 new-session -t $session
else
  exec -a $name $term -e tmux -2 new-session -s $session $shell
fi
