#!/bin/sh
#set -x -e
name=$(basename $0)
cmd=${name%%tmux}
export TERM=screen-256color-bce
tmux -2 has-session  2>/dev/null
if [ $? -eq 0 ]; then
   aflag=$(tmux -2 ls |grep attached )
   echo ${#aflag}
   if [ ${#aflag} -ge 5 ]; then
      #killall $cmd
      exec -a $name $cmd -e tmux -2 new-session&
      echo already on
   else 
     exec -a $name $cmd -e tmux -2 attach -d&
   fi
else
  exec -a $name $cmd -e tmux -2 new -s x&
fi
